name: cicd
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.20
          cache: false
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.20
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          args: --config=.golangci.yaml
